name: Firmware CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'firmware/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'firmware/**'

jobs:
  build:
    name: Build ESP-IDF Target
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive # specifically to pull lvgl components
        
    - name: Build Firmware for ESP32-S3
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1
        target: esp32s3
        path: 'firmware'
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: parakram-firmware-esp32s3
        path: |
          firmware/build/parakram.bin
          firmware/build/bootloader/bootloader.bin
          firmware/build/partition_table/partition-table.bin
